-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Profiles Table (Linked to Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  email text,
  avatar_url text,
  full_name text,
  website text,
  updated_at timestamp with time zone,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS) for Profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Handle new user signup automatically
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create Posts Table
create table posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  wallet_address text, -- For wallet-only users
  author_name text,
  author_handle text,
  content text not null,
  likes integer default 0,
  reposts integer default 0,
  liked_by jsonb default '[]'::jsonb,
  reposted_by jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  constraint content_length check (char_length(content) > 0 and char_length(content) <= 280)
);

-- Set up RLS for Posts
alter table posts enable row level security;

create policy "Posts are viewable by everyone."
  on posts for select
  using ( true );

create policy "Authenticated users can create posts."
  on posts for insert
  with check ( auth.role() = 'authenticated' );

-- Create Wallets Tracking Table (for "Wallets" view)
create table tracked_wallets (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    address text not null,
    label text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table tracked_wallets enable row level security;

create policy "Users can view their own tracked wallets."
  on tracked_wallets for select
  using ( auth.uid() = user_id );

create policy "Users can add wallets to track."
  on tracked_wallets for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their tracked wallets."
  on tracked_wallets for delete
  using ( auth.uid() = user_id );
